$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$base='03d62ad22438344f1dcd38c5b5e44f660b564b92';$tree0='a71d05341ad927c1c3fb7ff56b04a2b52aa2beb1';$parent0='92ee02584cae06cc4feace76dcbfdaadcca225e3a005b1038246850fa154c485'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$diag=Join-Path $env:RUNNER_TEMP 'bbx-patchfix3-diagnostics';New-Item -ItemType Directory $diag -Force|Out-Null;$replay=$null
function D($n,$v){$v|Set-Content (Join-Path $diag $n) -Encoding utf8}
function PSOK($p,$n){$tok=$null;$err=$null;[System.Management.Automation.Language.Parser]::ParseFile($p,[ref]$tok,[ref]$err)|Out-Null;if($err.Count-ne0){D $n (($err|ForEach-Object{$_.ToString()}) -join "`n");throw "PowerShell syntax validation failed: $p"};D $n "PASS $p"}
function FP($r){$p=@((git -C $r diff --name-only --diff-filter=ACMRTUXB)+(git -C $r ls-files --others --exclude-standard)|?{$_ -and $_ -notmatch '^(build-clean1|clean1_[^/]*)'}|sort -Unique);@($p|%{$f=Join-Path $r $_;if(Test-Path $f -PathType Leaf){$h=(Get-FileHash $f -Algorithm SHA256).Hash.ToLowerInvariant();"$h  $($_.Replace('\','/'))"}})}
try{
 $head=(git -C $root rev-parse HEAD).Trim();$cand=$head;if($env:GITHUB_EVENT_PATH -and(Test-Path $env:GITHUB_EVENT_PATH)){$e=gc $env:GITHUB_EVENT_PATH -Raw|ConvertFrom-Json;if(($e.PSObject.Properties.Name -contains 'pull_request')-and $e.pull_request -and $e.pull_request.head.sha){$cand=[string]$e.pull_request.head.sha}};D 'candidate-identity.txt' "event=$env:GITHUB_EVENT_NAME`nmerge_or_event_sha=$env:GITHUB_SHA`ncheckout=$head`ncandidate=$cand";if($head-ne$cand){throw 'candidate checkout mismatch'}
 $t=(git -C $root rev-parse "$base`^{tree}").Trim();if($t-ne$tree0){throw "baseline tree mismatch $t"}
 $bo=Join-Path $root '.bbx\ci\BUILD_TIERB_CLEAN1_PATCHFIX3.ps1';$lp=Join-Path $root '.bbx\ci\run_blackbox_patchfix3.ps1';$lc=Join-Path $root '.bbx\ci\run_blackbox_patchfix3.cmd';foreach($p in @($bo,$lp,$lc)){if(!(Test-Path $p)){throw "missing harness $p"}};PSOK $bo 'build-script-syntax.txt';PSOK $lp 'launcher-script-syntax.txt'
 try{& $bo -CompilerGateSelfTest 2>&1|Tee-Object (Join-Path $diag 'compiler-gate-fixtures.txt')}catch{D 'compiler-gate-fixtures-error.txt' ($_|Out-String);throw}
 $s=(gc (Join-Path $root '.bbx\ci\bootstrap_patchfix2.ps1') -Raw).Replace("`r`n","`n").Replace('bbx-patchfix2-diagnostics','bbx-patchfix3-diagnostics').Replace('PATCHFIX2','PATCHFIX3').Replace('patchfix2','patchfix3')
 $a='    Save-Diag "apply-result.txt" "PATCHFIX1_APPLY_PASS"'+"`n`n"+'    Push-Location $src';$b=@'
    Save-Diag "apply-result.txt" "PATCHFIX1_APPLY_PASS"
    Copy-Item (Join-Path $RepoRoot ".bbx\ci\BUILD_TIERB_CLEAN1_PATCHFIX3.ps1") (Join-Path $src "ci\BUILD_TIERB_CLEAN1.ps1") -Force
    Copy-Item (Join-Path $RepoRoot ".bbx\ci\run_blackbox_patchfix3.ps1") (Join-Path $src "tools\bb_blackbox\run_blackbox.ps1") -Force
    Copy-Item (Join-Path $RepoRoot ".bbx\ci\run_blackbox_patchfix3.cmd") (Join-Path $src "tools\bb_blackbox\run_blackbox.cmd") -Force

    Push-Location $src
'@;if(!$s.Contains($a)){throw 'apply injection anchor missing'};$s=$s.Replace($a,$b.TrimEnd("`r","`n"));$s=$s.Replace('        --no-compiler-runtime --no-system-d3d-compiler --no-system-dxc-compiler `','        --no-system-d3d-compiler --no-system-dxc-compiler `')
 $a='    Copy-Item -LiteralPath (Join-Path $src "tools\bb_blackbox\run_blackbox.cmd") -Destination (Join-Path $runtime "tools\bb_blackbox\run_blackbox.cmd") -Force'+"`n"+'    Copy-Item -LiteralPath (Join-Path $src "tools\bb_blackbox\decode.py") -Destination (Join-Path $runtime "tools\bb_blackbox\decode.py") -Force';if(!$s.Contains($a)){throw 'package copy anchor missing'};$s=$s.Replace($a,$a+"`n"+'    Copy-Item -LiteralPath (Join-Path $src "tools\bb_blackbox\run_blackbox.ps1") -Destination (Join-Path $runtime "tools\bb_blackbox\run_blackbox.ps1") -Force')
 $a='        "tools\bb_blackbox\run_blackbox.cmd",'+"`n"+'        "tools\bb_blackbox\decode.py",';if(!$s.Contains($a)){throw 'required list anchor missing'};$s=$s.Replace($a,'        "tools\bb_blackbox\run_blackbox.cmd",'+"`n"+'        "tools\bb_blackbox\run_blackbox.ps1",'+"`n"+'        "tools\bb_blackbox\decode.py",')
 $tmp=Join-Path $env:RUNNER_TEMP 'bootstrap_patchfix3_effective.ps1';[IO.File]::WriteAllText($tmp,$s,[Text.UTF8Encoding]::new($false));D 'effective-bootstrap-sha256.txt' ((Get-FileHash $tmp -Algorithm SHA256).Hash.ToLowerInvariant());PSOK $tmp 'effective-bootstrap-syntax.txt';& $tmp
 $src=Join-Path $env:RUNNER_TEMP 'bb-clean1-patchfix3-source';$pkg=Join-Path $env:RUNNER_TEMP 'ready4-patchfix3-package';$apply=Get-ChildItem $pkg -Recurse -Filter APPLY_CLEAN1_SOURCE_READY.ps1|select -First 1;if(!$apply){throw 'apply script missing'};$pr=$apply.Directory.Parent.FullName;$pp=Get-ChildItem $pr -Recurse -Filter INTEGRATED_R3_SAVEFIX_S1.patch|select -First 1;if(!$pp){throw 'parent missing'};$ph=(Get-FileHash $pp.FullName -Algorithm SHA256).Hash.ToLowerInvariant();if($ph-ne$parent0){throw 'parent hash mismatch'};D 'parent-sha256.txt' $ph
 $replay=Join-Path $env:RUNNER_TEMP 'bb-clean1-patchfix3-replay';git -C $root worktree add --detach $replay $base;if($LASTEXITCODE-ne0){throw 'replay worktree failed'};git -C $replay submodule update --init --recursive;if($LASTEXITCODE-ne0){throw 'replay submodules failed'};& $apply.FullName -RepoRoot $replay;if($LASTEXITCODE-ne0){throw 'replay apply failed'};cp $bo (Join-Path $replay 'ci\BUILD_TIERB_CLEAN1.ps1') -Force;cp $lp (Join-Path $replay 'tools\bb_blackbox\run_blackbox.ps1') -Force;cp $lc (Join-Path $replay 'tools\bb_blackbox\run_blackbox.cmd') -Force;$x=FP $src;$y=FP $replay;$c=Compare-Object $x $y;$x|sc (Join-Path $diag 'compiled-source-fingerprint.txt');$y|sc (Join-Path $diag 'replay-source-fingerprint.txt');if($c){throw 'independent replay differs'};D 'replay-equivalence.txt' 'INDEPENDENT_REPLAY_EQUIVALENCE=PASS'
 $zip=Join-Path $env:RUNNER_TEMP 'BLACKBOX_V1_CI_CLEAN1_PATCHFIX3_WIN64_QT.zip';$open=Join-Path $env:RUNNER_TEMP 'runtime-clean1-patchfix3-reopened';if(Test-Path $open){rm $open -Recurse -Force};Expand-Archive $zip $open;$mf=Join-Path $open 'SHA256SUMS-CLEAN1-RUNTIME.txt';foreach($l in gc $mf){if($l-notmatch'^([0-9a-f]{64})  (.+)$'){throw 'bad manifest'};$f=Join-Path $open ($Matches[2].Replace('/','\'));if(!(Test-Path $f)-or(Get-FileHash $f -Algorithm SHA256).Hash.ToLowerInvariant()-ne$Matches[1]){throw "package manifest mismatch $($Matches[2])"}};D 'package-reopen.txt' 'PACKAGE_REOPEN_MANIFEST=PASS'
 @('CAPTURE_READINESS=NOT_READY','RUNTIME_TEST_ALLOWED=false','unresolved=submit identity collision; query lifecycle/final collection; CONTROL query inactivity; frame/present semantics; nested GPU duration semantics')|sc (Join-Path $open 'CAPTURE-READINESS.txt') -Encoding ascii;$m=Get-ChildItem $open -Recurse -File|?{$_.Name-ne'SHA256SUMS-CLEAN1-RUNTIME.txt'}|sort FullName|%{$r=[IO.Path]::GetRelativePath($open,$_.FullName).Replace('\','/');$h=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant();"$h  $r"};$m|sc $mf -Encoding ascii;rm $zip;Compress-Archive (Join-Path $open '*') $zip -CompressionLevel Optimal
 $sm=Join-Path $env:RUNNER_TEMP 'bbx-patchfix3-smoke';New-Item -ItemType Directory $sm -Force|Out-Null;$cpp=Join-Path $sm 'p.cpp';@'
#include "common/bb_blackbox/recorder.h"
#include "common/bb_blackbox/schema.h"
#include "common/bb_blackbox/sites.h"
int main(){namespace B=Common::Blackbox;auto&r=B::Recorder::Instance();if(!r.InitializeFromEnvironment())return 20;for(unsigned long long i=0;i<3000;i++)if(r.Emit(B::EventId::Heartbeat,B::Site::Unknown,B::EventFlags::None,B::PayloadKind::None,i,0,0)==0)return 21;r.ShutdownProducer();return 0;}
'@|sc $cpp -Encoding ascii;$sx=Join-Path $sm 'p.exe';& 'C:\LLVM19\bin\clang-cl.exe' /nologo /std:c++20 /EHsc /O2 /DNOMINMAX /DWIN32_LEAN_AND_MEAN "/I$src\src" $cpp (Join-Path $src 'src\common\bb_blackbox\recorder.cpp') "/Fe:$sx" 2>&1|sc (Join-Path $diag 'synthetic-build.txt');if($LASTEXITCODE-ne0){throw 'synthetic build failed'};Push-Location $sm;try{& (Join-Path $open 'tools\bb_blackbox\run_blackbox.cmd') $sx 2>&1|Tee-Object (Join-Path $diag 'synthetic-launcher.txt');if($LASTEXITCODE-ne0){throw 'synthetic launcher failed'}}finally{Pop-Location};$cap=Get-ChildItem $sm -Directory -Filter 'BB_BLACKBOX_*'|sort LastWriteTimeUtc -Descending|select -First 1;if(!$cap){throw 'no synthetic capture'};$out=(python (Join-Path $open 'tools\bb_blackbox\decode.py') $cap.FullName|Out-String);$out|sc (Join-Path $diag 'synthetic-decode.json');$j=$out|ConvertFrom-Json;if(!$j.capture_complete-or[int64]$j.event_count-lt3000-or!$j.event_loss_free){throw 'synthetic smoke invalid'};D 'smoke-pass.txt' "SMOKE_PASS=true`ndecoded_events=$($j.event_count)"
 $zh=(Get-FileHash $zip -Algorithm SHA256).Hash.ToLowerInvariant();D 'runtime-zip-sha256.txt' $zh;D 'result.txt' "SOURCE_VALIDATED=true`nWINDOWS_BUILD_PASS=true`nPACKAGE_PASS=true`nSMOKE_PASS=true`nCAPTURE_READINESS=NOT_READY`nRUNTIME_TEST_ALLOWED=false`nRUNTIME_ZIP_SHA256=$zh";Write-Host "BLACKBOX_PATCHFIX3_PASS sha256=$zh capture_readiness=NOT_READY"
}catch{D 'failure.txt' ($_|Out-String);throw}finally{if($replay-and(Test-Path $replay)){try{git -C $root worktree remove --force $replay|Out-Null}catch{}}}
